---
- name: <TASK NAME>
  module_defaults:
    group/vmware: "{{  }}"

  tasks:
    - name: set connection info
      ansible.builtin.set_fact:
        connection_args:
          vcenter_hostname: "hostname"
          vcenter_username: "username"
          vcenter_password: "password"
          vcenter_validate_certs: "false"